Update Install

diff --git a/Install b/Install
--- a/Install
+++ b/Install
@@ -52,10 +52,10 @@ echo -n "Selected number: "
 read i
 case "$i" in
 1)
-    https://github.com/Chrisisthebestfhcigcyi/WineBox/releases/tag/Glibc
+    INSTALL_WOW64=0
 ;;
 2)
-    https://github.com/Chrisisthebestfhcigcyi/WineBox/releases/tag/Glibc
+    
 ;;
 *)
     return 1
@@ -64,3 +64,34 @@ esac
 
 echo "Installing WineBox"
 
+function wget-git-q {
+    wget -q --retry-connrefused --tries=0 --header "PRIVATE-TOKEN: $PRIVATE_TOKEN" "https://gitlab.com/api/v4/projects/$PROJECT_ID/repository/files/$1/raw?ref=main" -O $2
+    return $?
+}
+
+echo "Updating package manager"
+mkdir -p $PREFIX/glibc/opt/package-manager/installed
+
+if [ "$INSTALL_WOW64" = "1" ]; then
+echo "PRIVATE_TOKEN=glpat-h5r7HjKoPKZPxmfg79xs
+PROJECT_ID=54240888">$PREFIX/glibc/opt/package-manager/token
+else
+echo "PRIVATE_TOKEN=glpat-Xs4HfrCkMpbedkPycqzP
+PROJECT_ID=52465323">$PREFIX/glibc/opt/package-manager/token
+fi
+
+. $PREFIX/glibc/opt/package-manager/token
+if ! wget-git-q "package-manager" "$PREFIX/glibc/opt/package-manager/package-manager"; then
+    echo "Download failed"
+    return 1
+fi
+. $PREFIX/glibc/opt/package-manager/package-manager
+sync-all
+
+if [ "$INSTALL_WOW64" = "1" ]; then
+sync-package wine-9.6-vanilla-wow64
+else
+sync-package wine-ge-custom-9.0
+fi
+
+ln -sf $PREFIX/glibc/opt/scripts/mobox $PREFIX/bin/mobox
